<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.1.1 setup script
 * Date: Sat, 30 Oct 2021 19:43:40 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: db [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'db';
$cfg['Servers'][$i]['host'] = 'db';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = '>#QS~,gB0uQFh=Y_@_GR$YR@hgK"3\'';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>